# -*- coding: utf-8 -*-
"""8-08-2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t0_MSu46hWQvrkXADId8R_cLlKN_bTpW
"""

#  ciclo while
import time
import os # manejo de sistemas operativo
import sys # liberia de manejo de sistemas comando bat
# este algoritmo lo que hace es medir el tiempo de ejecucion de un ciclo while y un ciclo for
# para ver cual es mas rapido
inicio= time.time()# tiempo de ejecucion  esta capturando el tiempo
contador =0 # contador
while contador < 10: # controlando el ciclo, es decir repitiendo hasta que
# se cumpla la condicion
    print(contador) # imprime el valor que tiene el contador
    #por cada rotacion del ciclo
    contador += 1# incrementa el contador
fin= time.time()# toma el tiempo que finalizo en contador
print("Tiempo transcurrido while:", fin-inicio)
inicio= time.time()# tiempo de ejecucion
for contador in range(10):
    print(contador)
fin= time.time()
print("Tiempo transcurrido for:", fin-inicio)
if sys.platform == "win32":
    print ("el sistemas operativo win 32")
    os.system('cls')
else:
    print("el sistema operativo es otro win 64")
    os.system('clear')

# manejo de fecha
from  datetime import datetime as dt # esta libreria puede servir para captura de fechas
#dt es abrviacion de datetime
fecha = dt.now()# esta capturando la fecha actual
print("fecha actual ", fecha)

"""https://docs.python.org/3/library/datetime.html"""

from datetime import datetime as dt
fecha = dt.now()
# generar un formato personalizado dia mes y año
print(fecha.strftime("%d/%m/%Y"))
# %d dia
#%m mes
# Y año
# formato texto o nombre del  de la fecha
# %A estod dicioendo el nombre del dia ejemplo HOy es vernes, muestra viernes
# %B es el nombre del mes ejemplo AGOSTO
print(fecha.strftime("%A,%d de %B de %Y" ))
print(fecha.strftime("%H:%M:%S"))

"""controlar cicloc on breck y  booleanos"""

""" vamos hacer un progarama que se detenga cuando cumpla
10 repeticiones  pero el mietras inicia e TRUE, cuado
se cumpla la codicion deb detener el programa"""
contador = 1
while True:
  if contador == 10:
    print(f"{contador} se cumplio la cantidad de repeticiones" )
    break

  contador+= 1

palabra = input("Ingrese una palabra: ")
palabraMayuscula = palabra.upper()
print(palabraMayuscula)
palabraMinuscula = palabra.lower()
print(palabraMinuscula)

# https://docs.python.org/es/3.13/library/stdtypes.html#bytearray.lower


palabra='Hola mundo'

print(f"{palabra.title()}")

"""https://mimo.org/glossary/python/datetime"""